services:
  - type: web
    name: portfolio-backend-app
    runtime: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: "Portfolio"
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: "sqlite"
      - key: SESSION_DRIVER
        value: "file"
      - key: CACHE_STORE
        value: "file"
      - key: QUEUE_CONNECTION
        value: "sync"
      - key: LOG_CHANNEL
        value: "stack"
      - key: LOG_LEVEL
        value: "error"
